### ISSUE TITLE
Missing Account Validation for Withdraw Functionality

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/pendulum-amm#22]
Pallet AMM.
`pub fn skim(origin: OriginFor<T>)`
There is no validation. Any account can call this extrinsic and retrieve money from pallet to caller address.

https://github.com/pendulum-chain/pendulum-amm/blob/master/pallet/src/lib.rs#L317-L339

Recommendation: Use `ensure_root` or add PalletStorage that will contains AccountId that can call skim method and use this storage for validation.

-- reported by @web3online : https://www.notion.so/satoshipay/Internal-AMM-Audit-e8310abc690f4db6b1d05f850767274d

**Comment by b-yap** [comment]
> There is no validation. Any account can call this extrinsic and retrieve money from pallet to caller address.  

comment from @ebma :
Is this really an issue? If someone notices an overflow of token reserves and calls this function, he will profit by receiving the difference. This way people (besides us) are incentivized to check for this issue. Otherwise we would have to monitor it ourselves. 

Just as a side note, the explanation for skim and sync is in chapter 3.2.2 of the [whitepaper](https://uniswap.org/whitepaper.pdf).

**Comment by ebma** [comment]
What do you think about this @b-yap? Should we restrict it?

**Comment by b-yap** [comment]
it's also stated at _3.7 Maximum token balance_:
> ... any user can call the skim() function to remove excess assets from the liquidity pool.

_[Note that any account is allowed to call skim because we don't know who deposited the tokens.](https://ethereum.org/es/developers/tutorials/uniswap-v2-annotated-code/)_

**Comment by ebma** [comment]
@b-yap great find, then let's maybe just close this issue as we don't need to restrict it.
