### ISSUE TITLE
Recreate AMM as substrate pallet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-amm#8]
We want to have the same AMM functionality not only as a smart contract but also as a pallet that can be used by Substrate chains. The pallet should be added to this repository.

- [ ] Create a new folder structure for the repository. I would suggest a folder structure as follows: 
 - `pallet/`
 - `smart_contract/`
 - `testchain/`
- [ ] Implement an AMM pallet that has the same functionality as the AMM smart contract. Consider using the [pallet template](https://github.com/substrate-developer-hub/substrate-node-template/tree/main/pallets/template/src) as a starting point. The public functions of the ink! smart contract should be implemented as extrinsics for the AMM pallet.
- [ ] <s>Add the pallet to a test chain and make sure that it works (and behaves exactly like the AMM smart contract). Maybe use the [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node#note) project as a starting point since it already has the contracts pallet.</s> 
For the testchain see #13

**Comment by b-yap** [comment]
@ebma
I have a question. I keep getting instantatiateWithCode error everytime i tried to Upload and Instantiate.
what is the correct values in the Deployment Constructor? 

or is this because the substrate-contracts-node  in its runtime, did not specify the chain extension?

**Comment by ebma** [comment]
Hey @b-yap, yes it is very likely failing due to the missing chain extension. I thought about it and for the AMM pallet you also need to have some kind of currency on the chain that your pallet can use. So it probably makes sense to first set up a testchain that you can use for testing pallet and smart contract. Since it might be a longer task, I created a new issue ticket #13 for this.
